### ISSUE TITLE
zákruty

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-routing#11]
Je možné v plánovači (najme pre bicykel) spraviť že sa budú uprdnostňovať priamejšie cesty nad síce technicky rýchlejšími ale prakticky nie, nakoľko každé odbočenie často generuje zníženie rýchlostí, dávanie prednosti...

**Comment by MichalPP** [comment]
nejaká turn penalty existuje https://github.com/FreemapSlovakia/freemap-routing/blob/master/oma-bicycle.lua#L545

asi nie ideálna..

**Comment by seg-on** [comment]
Hej, dík už som to medzičasom objavil.
Vyzerá to byť celkom prepracované ten výpočet. keby sa dalo vidieť hodnoty v mape možno by to bolo zaujímavé na ladenie. Ale jasné že to je už dosť špecifická oblasť hrať sa so zákrutami..
