### ISSUE TITLE
routing bicycle=no for bicycle

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-routing#13]
It is possible routing bicycle track that are not for bicycle but allowed for pedestrian? Exactly with the tag bicycle=no. Cyklist will go this part by foot like on highway=footway.

**Comment by MichalPP** [comment]
correct tagging should by `bicycle=dismount` (not `bicycle=no`)

I think that `vehicle=no` (and foot allowed) should allow pushing bike

**Comment by seg-on** [comment]
OK thanks. I change it.
