### ISSUE TITLE
Navigacia pre auto ignoruje cesty znacene ako plochy

### ISSUE THREAD

**Issue by tjamecny** [FreemapSlovakia/freemap-routing#15]
Priklad pre [auto](https://www.freemap.sk/?map=18/49.152426/18.677039&layers=T&tool=route-planner&points=49.151942/18.677976,49.151598/18.677707&transport=car)

Ak ale zmenim typ hladania na "[foot](https://www.freemap.sk/?map=18/49.152426/18.677039&layers=T&tool=route-planner&points=49.151942/18.677976,49.151598/18.677707&transport=foot)", tak zrazu to vie najst.

"Problemova" cesta: https://www.openstreetmap.org/way/32620416

**Comment by MichalPP** [comment]
lepšie?

**Comment by tjamecny** [comment]
Už je to v poriadku, vďaka.
