### ISSUE TITLE
Závory na cyklotrasách a poľných cestách

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/freemap-routing#16]
Na lesných cestách sa často nachádzajú závaory ktoré slúžia na zabráneniu prechodu motorových vozidiel. Tieto brány by ale nemali tvoriť prekážku pre bicykel. Potom častokrát nie je možné naplánovať cestu aj po oficiálnych cyklotrasách.

**Comment by MichalPP** [comment]
ako su tagovane? resp aky je typicky priklad?

**Comment by seg-on** [comment]
barrier=swing gate
https://www.freemap.sk/?map=16/48.606766/17.960393&layers=C&tool=route-planner&points=48.603929/17.964857,48.603503/17.965586&transport=bike
https://www.openstreetmap.org/node/4680431914

**Comment by tjamecny** [comment]
Taktiež barrier=lift_gate: https://www.openstreetmap.org/node/4366494482

Ak sa dá, tak spraviť podmienku v štýle:
`if (((barrier == lift_gate) OR (barrier == swing_gate)) AND
    ((bicycle not set) OR (bicycle != no)) AND
    ((access not set) OR (access != private)))
then bicycle=yes`

**Comment by MichalPP** [comment]
@tjamecny je to trochu zložitejšie: https://github.com/FreemapSlovakia/freemap-routing/blob/master/oma-bicycle.lua#L44 po riadok 86 to nastavuje. ale mením to na whitelist 

https://github.com/Project-OSRM/osrm-backend/issues/3890

**Comment by MichalPP** [comment]
lepšie?

**Comment by tjamecny** [comment]
Za mňa je to už v poriadku, vďaka.

**Comment by seg-on** [comment]
U mňa tiež. díki :)
