### ISSUE TITLE
not routing bicycle on tunk_link

### ISSUE THREAD

**Issue by zdila** [FreemapSlovakia/freemap-routing#17]
I had to add bicycle=yes on https://www.openstreetmap.org/way/23811251 (there is a bicycle route) but I am not sure if all tunk_links should automatically forbid bicycle access.

**Comment by MichalPP** [comment]
anything not here https://github.com/FreemapSlovakia/freemap-routing/blob/master/oma-bicycle.lua#L105 is not allowed.

**Comment by zdila** [comment]
Then please add it there or just close this issue without a change. I'll leave it up on you :-)

**Comment by MichalPP** [comment]
closing, as motorways should be banned by default
