### ISSUE TITLE
increase the coverage

### ISSUE THREAD

**Issue by zdila** [FreemapSlovakia/freemap-routing#18]
At least SK, HU, PL, CS. Or whole Europe :-). How much would it cost regarding resources?

**Comment by MichalPP** [comment]
currently we have the same as srtm data. plus some cities around the world (eg https://routing.epsilon.sk/bikesharing.php )

**Comment by zdila** [comment]
Which SRTM data? What is the BBox? I'd like eg. [this](https://www.freemap.sk/?map=8/49.610710/15.257263&layers=O&tool=route-planner&points=50.085344/14.430542,49.192474/16.633301&transport=car) to work.

**Comment by MichalPP** [comment]
car profile extended, better?

**Comment by zdila** [comment]
Better, but still not enough: https://www.freemap.sk/?map=9/50.157546/13.798828&layers=O&tool=route-planner&points=50.064192/14.430542,50.080057/12.378845&transport=car

And what about hiking & bicycle? :)

**Comment by zdila** [comment]
@MichalPP maybe you can close it now
