### ISSUE TITLE
Add support for roundtrip=false

### ISSUE THREAD

**Issue by zdila** [FreemapSlovakia/freemap-routing#19]
Add support for `roundtrip=false` if it is not difficult.

Works: https://routing.epsilon.sk/trip/v1/foot/20.858573913574222,49.007812199150564;20.87162017822266,49.04664484986061;20.884666442871097,49.01963404018746?steps=true&geometries=geojson&roundtrip=true&source=first

Doesn't work: https://routing.epsilon.sk/trip/v1/foot/20.858573913574222,49.007812199150564;20.87162017822266,49.04664484986061;20.884666442871097,49.01963404018746?steps=true&geometries=geojson&roundtrip=false&source=first

**Comment by MichalPP** [comment]
works with `destination=last` added at the end

https://routing.epsilon.sk/trip/v1/foot/20.858573913574222,49.007812199150564;20.87162017822266,49.04664484986061;20.884666442871097,49.01963404018746?steps=true&geometries=geojson&roundtrip=false&source=first&destination=last
(original ticket: https://github.com/Project-OSRM/osrm-backend/issues/3828)

could you change UI call?

**Comment by zdila** [comment]
I see. Then it changes the game.
