### ISSUE TITLE
Routing pre peších nefunguje cez barrier=swing_gate

### ISSUE THREAD

**Issue by tjamecny** [FreemapSlovakia/freemap-routing#23]
Aj keď barrier=swing_gate nemá tag access, routovanie peších nefunguje po danej ceste. Pravdepodobne je to tak už prednastavené, lebo rovnaký problém sa vyskytuje aj v OSM OSRM. Routovane cyklistov funguje v pohode.
OSM objekt: https://www.openstreetmap.org/node/6556175073
Freemap OSRM: https://www.freemap.sk/?map=18/48.716767/19.045124&layers=T&tool=route-planner&points=48.716776/19.045288%2C48.716779/19.045342&transport=foot-osm&osm-node=519187350

![image](https://user-images.githubusercontent.com/16599347/116789833-2c0e4c80-aab1-11eb-9e24-4fa4a81d0748.png)

OSM OSRM: https://www.openstreetmap.org/directions?engine=fossgis_osrm_foot&route=48.71674%2C19.04528%3B48.71674%2C19.04535

![image](https://user-images.githubusercontent.com/16599347/116789863-6d9ef780-aab1-11eb-87b8-cc6a73eae30d.png)

(Pôvodne nahlásené na freemap email 1.5.2021 11:11).

**Comment by MichalPP** [comment]
bug report nemá nič spoločné s týmto routingom

**Comment by tjamecny** [comment]
OK, a do ktorého repository mám túto Issue presunúť?
