### ISSUE TITLE
nie je celkom jasne, preco cyklorouter odmieta navigovat po cyklotrase

### ISSUE THREAD

**Issue by jose1711** [FreemapSlovakia/freemap-routing#24]
Tu je dobre vidiet problem - miesto par metrov dlhej spojky je navrhovana trasa vedena obklukou

https://www.freemap.sk/?map=18/48.226613/17.199633&layers=X&tool=route-planner&points=48.225552/17.197487%2C48.226417/17.199461&transport=bike-osm

**Comment by MichalPP** [comment]
link čo si poslal je na nemecký server, o tom netuším ako funguje

keď prepnem na náš, tak dané cesty majú tag `construction`, čo (asi) [neroutuje](https://github.com/FreemapSlovakia/freemap-routing/blob/master/oma-bicycle.lua#L195)

**Comment by jose1711** [comment]
dakujem za nakopnutie, to bude ono. ten kluc som odstranil, bez `*=construction` nema vyznam a ten usek cesty je normalne zjazdny. inak doteraz som zil v tom, ze routing engine smeruje dotazy vzdy na ten nemecky server. vyzera vsak, ze sa pouziva len pri vybere `Bicykel` a `Pešo`, inak je routing v nasej rezii.
